name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-file-processing-transcription:
    name: Test file-processing-transcription
    runs-on: ubuntu-latest

    steps:
    - name: Check out file-processing-transcription code
      uses: actions/checkout@v3

    - name: Clone file-processing repository for Dockerfile
      run: |
        git clone https://github.com/hc-sc-ocdo-bdpd/file-processing.git

    - name: Build Docker image for file-processing-transcription
      run: |
        docker build -t file-processing-transcription-tests ./file-processing

    - name: Run tests for file-processing-transcription
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app file-processing-transcription-tests pytest tests

  test-file-processing:
    name: Test file-processing
    runs-on: ubuntu-latest

    steps:
    - name: Clone file-processing repository
      uses: actions/checkout@v3
      with:
        repository: hc-sc-ocdo-bdpd/file-processing
        path: file-processing

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.4

    - name: Build Docker image for file-processing
      run: |
        cd file-processing
        docker build -t file-processing-tests .

    - name: Run tests for file-processing
      run: |
        docker run --rm file-processing-tests pytest tests/unit
        docker run --rm file-processing-tests pytest tests/integration